SET "SAUCENAO=E:\Users\YouYouAndYourself\SauceNao-Windows.exe"
SET "SAUCENAO_API_KEY=YOUR-API-KEY"
SET "IMGUR_API_KEY=YOUR-API-KEY"
SET "PROXY=IP:PORT"

SET COMMAND=%SAUCENAO% %SAUCENAO_API_KEY% %IMGUR_API_KEY% %%1 %PROXY%

%SystemRoot%\System32\reg.exe ADD HKEY_CLASSES_ROOT\*\shell\SauceNAO!\command /ve /d "%COMMAND%" /f >nul
